# Generated by Django 3.1.3 on 2021-04-14 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tuser',
            fields=[
                ('user_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('user_name', models.CharField(blank=True, max_length=10, null=True)),
                ('user_pwd', models.CharField(blank=True, max_length=10, null=True)),
                ('occ_no', models.IntegerField()),
            ],
            options={
                'db_table': 'tuser',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Occupations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occ', models.CharField(choices=[('1', 'others')], max_length=50)),
                ('occ_no', models.ForeignKey(db_column='occ_no', on_delete=django.db.models.deletion.CASCADE, related_name='tuser', to='accounts.tuser')),
            ],
        ),
    ]
