# Generated by Django 3.1.3 on 2021-04-15 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occupations',
            name='occ',
            field=models.CharField(choices=[('1', '경영, 사무'), ('2', '생산, 제조'), ('3', '영업, 고객상담'), ('4', '전문직'), ('5', 'IT, 인터넷'), ('6', '교육'), ('7', '미디어'), ('8', '특수계층, 공공'), ('9', '건설'), ('11', '유통, 무역'), ('12', '서비스'), ('13', '디자인'), ('14', '의료'), ('15', '학생'), ('16', '주부'), ('0', '기타')], default='1', max_length=50),
        ),
        migrations.AlterField(
            model_name='occupations',
            name='occ_no',
            field=models.ForeignKey(db_column='occ_no', on_delete=django.db.models.deletion.CASCADE, related_name='auth_user', to='accounts.tuser'),
        ),
    ]
