# Generated by Django 3.0.8 on 2021-04-27 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210415_1634'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='occupations',
            options={'managed': False},
        ),
    ]
