# Generated by Django 3.0.8 on 2021-03-11 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('tourid', models.IntegerField(db_column='tourId', primary_key=True, serialize=False)),
                ('city', models.CharField(blank=True, max_length=10, null=True)),
                ('town', models.CharField(blank=True, max_length=20, null=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('genre', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'travel',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Treview',
            fields=[
                ('treview_no', models.AutoField(primary_key=True, serialize=False)),
                ('treview_id', models.CharField(blank=True, max_length=20, null=True)),
                ('tourid', models.IntegerField(blank=True, db_column='tourId', null=True)),
                ('rating', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'treview',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tuser',
            fields=[
                ('user_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('user_name', models.CharField(blank=True, max_length=10, null=True)),
                ('user_pwd', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'tuser',
                'managed': False,
            },
        ),
    ]
