# Generated by Django 3.1.3 on 2021-04-14 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tuser',
        ),
    ]
