# Generated by Django 3.0.8 on 2021-05-01 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0002_delete_tuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tuser',
            fields=[
                ('user_no', models.AutoField(primary_key=True, serialize=False)),
                ('genre', models.IntegerField(blank=True, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('occ', models.IntegerField(blank=True, null=True)),
                ('gen', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tuser',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usert',
            fields=[
                ('userid', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=20)),
                ('password2', models.CharField(max_length=20)),
                ('etc', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'usert',
                'managed': False,
            },
        ),
    ]
