# Generated by Django 3.1.3 on 2021-06-07 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0003_tuser_usert'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tresult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place1', models.IntegerField(blank=True, db_column='PLACE1', null=True)),
                ('place2', models.IntegerField(blank=True, db_column='PLACE2', null=True)),
                ('place3', models.IntegerField(blank=True, db_column='PLACE3', null=True)),
                ('place4', models.IntegerField(blank=True, db_column='PLACE4', null=True)),
                ('place5', models.IntegerField(blank=True, db_column='PLACE5', null=True)),
                ('udate', models.DateTimeField(blank=True, db_column='UDATE', null=True)),
            ],
            options={
                'db_table': 'tresult',
                'managed': False,
            },
        ),
    ]
